name: Build and Push CloudPanel Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get_version.outputs.version }}
      needs_build: ${{ steps.compare_versions.outputs.needs_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest CloudPanel release
        id: get_version
        run: |
          latest_version=$(curl -s https://api.github.com/repos/cloudpanel-io/cloudpanel-ce/releases/latest | jq -r .tag_name)
          echo "Latest release: $latest_version"
          echo "version=$latest_version" >> $GITHUB_ENV
          echo "::set-output name=version::$latest_version"

      - name: Compare with existing version
        id: compare_versions
        run: |
          current_version=$(cat version.txt 2>/dev/null || echo "none")
          if [ "$current_version" != "${{ env.version }}" ]; then
            echo "New version available: ${{ env.version }}"
            echo "${{ env.version }}" > version.txt
            echo "needs_build=true" >> $GITHUB_ENV
            echo "::set-output name=needs_build::true"
          else
            echo "Already up-to-date"
            echo "needs_build=false" >> $GITHUB_ENV
            echo "::set-output name=needs_build::false"
          fi
      - name: Commit updated version
        if: steps.compare_versions.outputs.needs_build == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version to ${{ env.version }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main


  build-and-push:
    needs: check-release
    if: needs.check-release.outputs.needs_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t your-dockerhub-username/cloudpanel:${{ needs.check-release.outputs.latest_version }} .
          docker tag your-dockerhub-username/cloudpanel:${{ needs.check-release.outputs.latest_version }} your-dockerhub-username/cloudpanel:latest

      - name: Push to Docker Hub
        run: |
          docker push your-dockerhub-username/cloudpanel:${{ needs.check-release.outputs.latest_version }}
          docker push your-dockerhub-username/cloudpanel:latest

